#ifndef token_h
#define token_h

enum TOKEN_TYPE
{
    AT,
    CASE,
    CLASS,
    COMMA,
    COLON,
    DIVISION,
    DOT,
    EQUALS,
    ELSE,
    ESAC,
    FALSE,
    FI,
    GEQUAL,
    GTHAN,
    IDENTIFIER,
    IF,
    IN,
    INHERITS,
    INTEGER,
    INTCOMPLEMENT,
    ISVOID,
    LARROW,
    LBRACKET,
    LEQUAL,
    LET,
    LOOP,
    LPAREN,
    LTHAN,
    MINUS,
    MULTI,
    NEW,
    NOT,
    OF,
    PLUS,
    POOL,
    RARROW,
    RBRACKET,
    RPAREN,
    SEMICOLON,
    STRING,
    THEN,
    TRUE,
    TYPE,
    WHILE
};

const char *const token_to_string[] = {
    [AT] = "AT",
    [CASE] = "CASE",
    [CLASS] = "CLASS",
    [COMMA] = "COMMA",
    [COLON] = "COLON",
    [DIVISION] = "DIVISION",
    [DOT] = "DOT",
    [EQUALS] = "EQUALS",
    [ELSE] = "ELSE",
    [ESAC] = "ESAC",
    [FALSE] = "FALSE",
    [FI] = "FI",
    [GEQUAL] = "GEQUAL",
    [GTHAN] = "GTHAN",
    [IDENTIFIER] = "IDENTIFIER",
    [IF] = "IF",
    [IN] = "IN",
    [INHERITS] = "INHERITS",
    [INTEGER] = "INTEGER",
    [INTCOMPLEMENT] = "INTCOMPLEMENT",
    [ISVOID] = "ISVOID",
    [LARROW] = "LARROW",
    [LBRACKET] = "LBRACKET",
    [LEQUAL] = "LEQUAL",
    [LET] = "LET",
    [LOOP] = "LOOP",
    [LPAREN] = "LPAREN",
    [LTHAN] = "LTHAN",
    [MINUS] = "MINUS",
    [MULTI] = "MULTI",
    [NEW] = "NEW",
    [NOT] = "NOT",
    [OF] = "OF",
    [PLUS] = "PLUS",
    [POOL] = "POOL",
    [RARROW] = "RARROW",
    [RBRACKET] = "RBRACKET",
    [RPAREN] = "RPAREN",
    [SEMICOLON] = "SEMICOLON",
    [STRING] = "STRING",
    [THEN] = "THEN",
    [TRUE] = "TRUE",
    [TYPE] = "TYPE",
    [WHILE] = "WHILE"};

#endif